### ISSUE TITLE
Regression in MobileBert on ARM after LLVM Integrate

### ISSUE THREAD

**Issue by mariecwhite** [openxla/iree#11357]
Latency increased by 14% on FP32 MobileBert ARM CPU after an LLVM Integrate.

![image](https://user-images.githubusercontent.com/5143063/204656960-c31e6d99-8976-4d37-840d-b3c330d05575.png)

**Comment by pzread** [comment]
Can you share the link to that graph?

**Comment by mariecwhite** [comment]
Graph link [here](https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%20big-core%2Cfull-inference%2Cdefault-flags%20with%20IREE-LLVM-CPU-Sync%20%40%20Pixel-6-Pro%20(CPU-ARMv8.2-A))

**Comment by hanhanW** [comment]
Narrow it down to

```
#map3 = affine_map<(d0, d1) -> (d0, d1)>
#map5 = affine_map<(d0, d1) -> (d1)>
func.func @main(%0 : tensor<384x128xf32>, %1 : tensor<128x512xf32>, %2 : tensor<512xf32>) -> tensor<384x512xf32>{
  %cst = arith.constant 3.40282347E+38 : f32
  %cst_0 = arith.constant 0.000000e+00 : f32
  %3 = tensor.empty() : tensor<384x512xf32>
  %4 = linalg.fill ins(%cst_0 : f32) outs(%3 : tensor<384x512xf32>) -> tensor<384x512xf32>
  %5 = linalg.matmul ins(%0, %1 : tensor<384x128xf32>, tensor<128x512xf32>) outs(%4 : tensor<384x512xf32>) -> tensor<384x512xf32>
  %6 = linalg.generic {indexing_maps = [#map5, #map3, #map3], iterator_types = ["parallel", "parallel"]} ins(%2, %5 : tensor<512xf32>, tensor<384x512xf32>) outs(%3 : tensor<384x512xf32>) {
  ^bb0(%in: f32, %in_1: f32, %out: f32):
    %7 = arith.addf %in, %in_1 : f32
    %8 = arith.minf %7, %cst : f32
    %9 = arith.maxf %8, %cst_0 : f32
    linalg.yield %9 : f32
  } -> tensor<384x512xf32>
  return %6 : tensor<384x512xf32>
}
```

Before the integrate: 1.36 ms
After the integrate: 2.0 ms

**Comment by hanhanW** [comment]
The IR dumps are identical until `SerializeTargetExecutablesPass`. It seems that the regression is because of LLVM changes.  The data in `hal.executable.binary public @embedded_elf_arm_64` is different.

@MaheshRavishankar I think we're going to move to data-tiling path for ARM; there are no regressions in mmt4d path. Is it fine to deprioritize the issue? If not, I can help dig into LLVM changes and see what's happening.

note: these are the related commits in the integrate: https://github.com/iree-org/iree-llvm-fork/compare/accc5519e35ab3c9ebb6d59baa07833412eef201...119cef40d18c48240854edc553dca61c4e9fdf27

**Comment by hanhanW** [comment]
I think this is because the `aarch64-enable-gep-opt` flag has been disabled by default: https://github.com/iree-org/iree-llvm-fork/commit/201b7858f6957d84bc75bd228224d7b28d7df61e

The matmul performance is 1.68 ms w/o the optimization. It is 1.1 ms w/ the optimization. I'll try run benchmarks w/ the flag. If it addresses the issue, we can think if we want to enable the option in IREE or not.

**Comment by hanhanW** [comment]
I verified that adding the flag fixes the issue, see https://github.com/openxla/iree/pull/12422

@bjacob @MaheshRavishankar could you help make a call here? We can either mark it as intended behavior or add the flag to our benchmark suite.

**Comment by hanhanW** [comment]
I verified that adding the flag fixes the issue, see https://github.com/openxla/iree/pull/12422

@bjacob @MaheshRavishankar could you help make a call here? We can either mark it as intended behavior or add the flag to our benchmark suite.

**Comment by benvanik** [comment]
If we want to force it on we can do it programmatically instead of by passing it on the command line (via llvm::cl::getRegisteredOptions + llvm::cl::ProvidePositionalOption and such, stella probably knows a better way).

**Comment by MaheshRavishankar** [comment]
Yeah, what Ben said... I think we should do it programmatically.... Hold on, let me dig up something

**Comment by MaheshRavishankar** [comment]
@hanhanW one thing you can do is to respond to the patch saying this causes regressions. If there was a way to do control this flag through the C++ API, that would help.... (let me know, I can do it too)

**Comment by benvanik** [comment]
It's kind of surprising that they rolled it back for some code size things given that it only seems to be enabled in -O3, where this kind of stuff is common: `if (TM->getOptLevel() == CodeGenOpt::Aggressive && EnableGEPOpt) {`

We could also try adding these passes directly, though I don't know if they need to run exactly where they are or not:
```c++
    addPass(createSeparateConstOffsetFromGEPPass(true));
    addPass(createEarlyCSEPass());
    addPass(createLICMPass());
```

**Comment by MaheshRavishankar** [comment]
Yeah, that is one of the options. Though I think having that exposed during setup of target machine might be something that would be more ergonomic.

**Comment by hanhanW** [comment]
Thanks for the advices! I dropped a comment on the patch: https://reviews.llvm.org/rG201b7858f6957d84bc75bd228224d7b28d7df61e

**Comment by antiagainst** [comment]
It seems this will take a while to resolve. For now I'll just mark the dashboard as "intended behavior" to the flagged regression, to avoid hide additional issues.

**Comment by allieculp** [comment]
@hanhanW Going to mark this as P1 'in progress' - please update if needed.

**Comment by MaheshRavishankar** [comment]
Leaving some notes here for help with triage of what I would do to start narrowing down the dispatch. Adding these flags will give you the IR for dispatch before and after most of the load bearing part of the IREE compilation.

```
--mlir-print-ir-before=iree-llvmcpu-lower-executable-target --mlir-print-ir-after=iree-llvmcpu-lower-executable-target --mlir-disable-threading --mlir-elide-elementsattrs-if-larger=4
```

If there are no differences before and after the integrate with these flags, then the issue comes down to a regression in LLVM.

**Comment by hanhanW** [comment]
The regression happens in matmul. Verified that there are no difference before and after the integrate. We've narrowed it down to LLVM commit. One of the pass is disabled by default under a flag. We can address the issue if the pass is included. It looks like there is no way to configure the passes through c++ program at this moment. See https://reviews.llvm.org/rG201b7858f6957d84bc75bd228224d7b28d7df61e for more details.

There are two options to me:

1. We can mark this as intended because the pass is impacting the precision.
2. We can enable the flag in our benchmark suite; allocate someone to expose the option programable. Then we can remove the flag from compilation flags.

Since we're progressing toward data-tiling approach and the ARM matmul codegen was developed 1.5 years ago, I'd +1 on option 1.

**Comment by MaheshRavishankar** [comment]
I wasnt sure if you were waiting on me to respond. Basically we cant do much here. The way this is gated (here https://github.com/llvm/llvm-project/blob/ffb42e313d5439827dde884b97e60ef2ddadcc38/llvm/lib/Target/AArch64/AArch64TargetMachine.cpp#L572) the only option is to not guard this with the LLVM global flag, and allow it to be controlled by `Aggressive` codegen option. or to change the `AArch64TargetMachine` constructor here(https://github.com/llvm/llvm-project/blob/ffb42e313d5439827dde884b97e60ef2ddadcc38/llvm/lib/Target/AArch64/AArch64TargetMachine.cpp#L317) to allow setting this option during target machine instantiation.

If we really want to fix this, needs LLVM changes. I'd vote for just living with this for now.

**Comment by hanhanW** [comment]
I'm not sure who is going to make the call. I'd also vote for living with this for now.. closing the issue since there are no further action items.
