### ISSUE TITLE
Building TF binaries got really slow

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#11396]
At some point between https://github.com/iree-org/iree/actions/runs/3474647715/jobs/5808049713 on 2022-11-15 and https://github.com/iree-org/iree/actions/runs/3520611520/jobs/5901682024 on 2022-11-21 building the TF binaries went from taking 5 minutes to 18 minutes

**Comment by GMNGeoffrey** [comment]
Hmm this is actually more complicated. When we update LLVM, the build gets slow because we don't have things cached (as expected), but now it seems that it isn't recovering. That makes me suspect an issue with writing to the cache, actually

**Comment by bhack** [comment]
I have not checked what cache you are using here but it was hard for me to use re-use also "the official" nightly remote cache:

https://github.com/tensorflow/tensorflow/pull/57630#issuecomment-1242711115

**Comment by GMNGeoffrey** [comment]
We've got our own cache, but it might suffer from similar problems to the official one. Thanks for the pointer

**Comment by GMNGeoffrey** [comment]
I haven't been prioritizing this because I'm hopeful we can get TF to soon produce its own compiler binaries that turn models into a canonical format we can consume and then we can just delete all this code

**Comment by bhack** [comment]
Do you mean OpenXLA + tsl?

**Comment by jpienaar** [comment]
No this is more related to the TF bridge team's work and the self-contained export TF pip package side. OpenXLA level comes post these binaries and TSL is something I doubt will be needed anywhere here. One piece of work that needs to be clarified there before we can deprecate the need here, but got pre-empted by more time sensitive discussions before folks were out.

**Comment by bhack** [comment]
Ah ok so if understand correctly it seems we will have (the new?) TF bridge self contained in a published wheel.

**Comment by jpienaar** [comment]
Yes indeed. We are very close to some version of that*. It has been missing for some time and the tool IREE side was used as such for a while, but that was more of a stopgap.

* There is more nuance but effectively it would be SavedModel in and (mostly) MLProgram & StableHLO out in bytecode format. I now want to add another footnote to explain the parenthesis, but lets rather focus on the future goal where we have stable interop here and can just pip install rather than be building at head because some stylistic change necessitated it :)

**Comment by bhack** [comment]
So if I am reading this correctly we have a sort of dependency on https://github.com/openxla/stablehlo/issues/216

**Comment by jpienaar** [comment]
Sort of, that bug is mostly just a task for switching MHLO and StableHLO as a drop in. We don't actually care how StableHLO is produced: StableHLO is the air gap dialect with upgrade hooks, whether bridge produced MHLO and then that got converted to StableHLO or bridge produces StableHLO directly is about even for us. https://github.com/iree-org/iree/issues/5095 is one of the first external ones I could find IREE side and https://github.com/iree-org/iree/issues/10849 is the response to that conversation (now there is a much older conversation here but I forgot where it happened, but if you squint you can match the pipeline there and what IREE had in import TF as a graduation to TF repo). Our dependency currently is on representing the input list types fully. So the currently landed changes gives the conversions but the "interface" section may be missing (things requiring https://github.com/iree-org/iree/tree/main/integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/Input). BUT I think those are more important if integrating into TF run proper vs where we aim to use it (and with PJRT becoming the new compiler interface mechanism even for TF), that may not be needed.

**Comment by GMNGeoffrey** [comment]
@dellis23 can you provide an update on your progress getting us out of the business of building TensorFlow?

**Comment by dellis23** [comment]
@GMNGeoffrey I have a draft available here: https://github.com/openxla/iree/pull/12758

I'm currently working on a couple of remaining issues: 1) can we migrate to using tf-nightly instead of the main tensorflow release, and 2) making sure benchmarks still work.  SHARK also has a number of benchmarks, but Jacques is talking with Anush about whether we need to test those.  Hopefully we'll be done once I get those resolved, but something has tended to pop up at every stage of working on this, so I wouldn't be surprised if something else is still lying in wait.

**Comment by jpienaar** [comment]
Anush and I agreed on regressions there being fine and requests up to TF team to address API. (I think we have a worst case of "run freeze graph" first for users affected by the functionality drop, not our favorite option, but bridge solution).

**Comment by GMNGeoffrey** [comment]
We've removed TF builds from the critical CI path with https://github.com/openxla/iree/pull/13025 and https://github.com/openxla/iree/pull/13057 and plan to remove it entirely as part of https://github.com/openxla/iree/issues/13037. I'm closing this issue as not planned
