### ISSUE TITLE
Feature request: support passing zero-copy cuda buffers to IREE

### ISSUE THREAD

**Issue by dellis23** [openxla/iree#11573]
### Request description

See https://discord.com/channels/689900678990135345/804403964463546378/1053046022626091130 for background

We'd like to be able to initialize a tensor on a cuda device and pass it to IREE, rather than having to initialize on a host device and force IREE to do a copy.  Ideally this would provide a Python API too.

### What component(s) does this issue relate to?

Runtime

**Comment by benvanik** [comment]
These two methods need to be implemented by someone: https://github.com/google/iree/blob/main/runtime/src/iree/hal/drivers/cuda/cuda_allocator.c#L300-L318
cuImportExternalMemory can be used for some of the types, and then we can have cuMemPoolImportPointer / cuMemPoolExportPointer for exchanging memory with other processes, etc.

**Comment by dellis23** [comment]
> These two methods need to be implemented by someone: https://github.com/google/iree/blob/main/runtime/src/iree/hal/drivers/cuda/cuda_allocator.c#L300-L318 cuImportExternalMemory can be used for some of the types, and then we can have cuMemPoolImportPointer / cuMemPoolExportPointer for exchanging memory with other processes, etc.

Is there an analogous existing flow for any other backend that's also plumbed through to Python? I wouldn't mind tinkering with it to see if I can hack something together.

**Comment by benvanik** [comment]
There are HAL methods for `iree_hal_allocator_import_buffer` and `iree_hal_allocator_export_buffer` so each driver can implement their own import/export semantics. They all use the `iree_hal_external_buffer_t` type which matches what Vulkan/D3D12/CUDA all support for external handles but it could also use some more enums - like `IREE_HAL_EXTERNAL_BUFFER_TYPE_DEVICE_ALLOCATION` that takes a void* device ptr (or VkBuffer etc) to go alongside the `IREE_HAL_EXTERNAL_BUFFER_TYPE_HOST_ALLOCATION` - this would let you pass a CUDA device pointer right in/get one out. We'll also be able to extend it over time for things like `AHardwareBuffer` on Android or `MTLBuffer` on iOS, etc.

Import is relatively straightforward but export will require a bit more goo as it has implications on the original allocation - to export a buffer it needs to be a dedicated allocation (instead of a suballocation) and unaliased and we may need some additional allocation flags to support that. If all you need is import to start that makes things easier, especially if ownership is retained with the caller (just letting IREE access the buffer but not trying to make IREE manage it).

I'm not sure if they're exposed to python but it should be pretty straightforward. The import call does take a callback that would need to be passed when ownership is transferred but that's just some pybind goo and we may use for other things already that shows how to deal with lifetime management.

**Comment by stellaraccident** [comment]
I'm interested in extending the python API in this way but it is friendly frighteningly easy to get wrong and my rule for that is to wait until there is demand...

**Comment by silvasean** [comment]
I think we have reached a point in the TorchDynamo integration that having this be zero-copy is necessary for IREE to go beyond "toy" status. So I would consider there to be "demand" here, unless we want to deprioritize IREE running under TorchDynamo for the time being.

**Comment by stellaraccident** [comment]
Just so that I understand what is being asked: you have device memory initialized and you need to create a DeviceArray from that (via import)? Exposing the API is relatively easy, but it would be really good to have a reduced test case and/or sample demonstrating these more advanced things without requiring a specific use (like torch).

Also just checking: you don't need to do any layout transformation?

**Comment by stellaraccident** [comment]
Any ideas on the test case are welcome... I'm happy to expose test only APIs for allocating raw device memory to do this if needed.

**Comment by silvasean** [comment]
Basically we have torch.Tensor's that have pointers to CUDA memory and need to compute on them with IREE and then get results back as CUDA buffers. On the input side it looks like:

```
>>> import torch
>>> t = torch.tensor([1,2,3]).cuda()
>>> t.data_ptr()
140402397020672
```

(probably doing this with CPU first would be an adequate scale model)

(if you need a quick colab to test this I found the instructions here for GPU colab useful: https://www.geeksforgeeks.org/how-to-run-cuda-c-c-on-jupyter-notebook-in-google-colaboratory/)

I'm not sure the output story, but it seems less pressing. Googling around, some [prior art](https://github.com/NVIDIA-AI-IOT/jetbot/blob/cf3e264ae636d803dcead0549e04b013249f0b30/jetbot/tensorrt_model.py#L119) in the ecosystem works exclusively with out params, which might be enough for us (TorchDynamo can always generate statically shaped code). I still need to look more into the buffer donation problem and see how we want to handle this, or whether truly escaping dynamic-sized cuda allocataions are necessary for IREE.

Especially for training loops we aren't going to want the truly escaping allocations anyway, so ignoring that case for a first step is probably fine.

**Comment by stellaraccident** [comment]
Thanks. Beyond that simple example, what are the chances that the real case has arbitrary strided layouts?

**Comment by stellaraccident** [comment]
Ok, and doing this for real for output buffers will require that we finally move past the basic calling convention where all outputs are returned imperatively. We have a different compilation mode with full async and signatures needed for these more advanced cases, but exercising it fell victim to holiday vacations. We need that working for pjrt integration anyway so need to get on it. I assume the needs are similar modulo python API exposure so fine pushing on this more -- it'd be good to have multiple users to get the apis and features right.

This will require some design work and that won't start until Monday, earliest. Then we'll have a better view of what we're looking at.

**Comment by silvasean** [comment]
> Thanks. Beyond that simple example, what are the chances that the real case has arbitrary strided layouts?

I haven't actually tested this, but I believe the chances of arbitrary strided layouts are low. Or even if there are, it will be for inputs (not huge weights [1]) and the captured graph will be large enough to amortize making them contiguous.

[1] In stock PyTorch the weights are the raw inputs to cudnn operators, so there is already a force keeping them away from being in random strided layouts.

**Comment by allieculp** [comment]
@silvasean @stellaraccident Curious if this is still active? Sounds like a P2 if it is.
