### ISSUE TITLE
Update Dockerfiles from Ubuntu 18.04 base

### ISSUE THREAD

**Issue by ScottTodd** [openxla/iree#11782]
Our base Dockerfile uses Ubuntu 18.04: https://github.com/iree-org/iree/blob/160349188b58b2704fd9f26ee6c1f7a8e2811cd2/build_tools/docker/dockerfiles/base.Dockerfile#L7-L8

According to https://wiki.ubuntu.com/Releases, Ubuntu 18.04 will reach "end of standard support" in April 2023 then "end of life" in April 2028. If updating to a more recent version like 20.04 or 22.04 is possible, it would be nice to do that work before 18.04 reaches end of support. 

https://hub.docker.com/_/ubuntu/

**Comment by GMNGeoffrey** [comment]
We deliberately test using the oldest Ubuntu version that we support, so that we actually ensure that it works. I actually think we were conflating "end of support" and "end of life" previously. Even 14.04 isn't EOL. I guess then that our policy is to support a version until it reaches the end of standard support. Ubuntu upgrades are pretty easy these days, so I don't think that's too unreasonable. I think we should avoid dropping it until *after* that window has ended though unless we have a particularly good reason.
